sonar.projectKey=airport_service
sonar.projectName=Airline-Management-Service
sonar.organization=amanfoundongithub

sonar.sources=src
sonar.tests=tests

sonar.language=py
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/*.db
sonar.test.inclusions=**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml