services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  auth-service:
    build: .
    ports:
      - "4500:4500"
    environment:
      - MONGO_URI=mongodb://db:27017/
      - MONGO_DB_NAME=auth_service
    depends_on:
      - db